### ISSUE TITLE
Questions on subsampling rate

### ISSUE THREAD

**Issue by steventan0110** [WPti/proxy-filter#2]
Hi authors of proxy-filter repo,

I was reading your paper published on WMT and I am very interested in your approach. I was trying to replicate the results and I'm wondering how to set the training subsample rate properly? In the [script](https://github.com/WPti/proxy-filter/blob/master/script/finetune.sh#L21), it's set as 0.1. From the paper, you mentioned that 2k and 10k samples are subsampled. However, if I use Pashto dataset which has about 10^6 lines, subsample with 0.1 is still much larger than 10k. Therefore I'm wondering if this value 0.1 should be adjusted or there is another argument that controls the amount of training data being used? Thanks for your clarification!

**Comment by hlkcrcck** [comment]
@steventan0110 hi, you can adjust the "training subsample rate" as you mentioned. You can also pre-split the parallel sentences and feed them to the fine-tuner if you want more precise control. Also if you have the compute power, there is no harm to provide more than 10k examples to the training.
